---
name: admin-ui

releases:
- name: admin-ui
  version: latest
- name: secureproxy
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000
  vm_strategy: create-swap-delete

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

instance_groups:
- name: admin-ui
  instances: 1
  azs: [z1]
  networks:
  - name: default
  vm_type: t3.medium
  vm_extensions: [admin-lb]
  persistent_disk_type: 10GB
  stemcell: default
  jobs:
  - name: secureproxy
    release: secureproxy
    properties:
      secureproxy:
        listen_port: 8080
        proxy_port: 8070
  - name: admin_ui
    release: admin-ui
    properties:
      admin_ui:
        cloud_controller_uri: ((cloud_controller_uri))
        cloud_controller_ssl_verify_none: false
        cookie_secret: ((admin_ui_cookie_secret))
        uaa:
          client:
            id: admin-ui
            secret: ((admin_ui_uaa_client_secret))
          scopes:
            admin: ~
            user: ~
        ccdb:
          scheme: ((terraform_outputs.cf_rds_engine))
          address: ((terraform_outputs.cf_rds_host))
          port: ((terraform_outputs.cf_rds_port))
          username: ((terraform_outputs.cf_rds_username))
          password: ((terraform_outputs.cf_rds_password))
          database: ccdb
        uaadb:
          scheme: ((terraform_outputs.cf_rds_engine))
          address: ((terraform_outputs.cf_rds_host))
          port: ((terraform_outputs.cf_rds_port))
          username: ((terraform_outputs.cf_rds_username))
          password: ((terraform_outputs.cf_rds_password))
          database: uaadb
      networks:
        apps: default
      nats:
        user: ((admin_ui_nats_user))
        password: ((admin_ui_nats_password))
        port: ((admin_ui_nats_port))
        machines: ((admin_ui_nats_machines))
        address: ((admin_ui_nats_address))


variables:
- name: admin_ui_cookie_secret
  type: password
- name: admin_ui_uaa_client_secret
  type: password
