cg-deploy-admin-ui-git-branch: test-deploy-jammy
cg-deploy-admin-ui-git-url: https://github.com/18F/cg-deploy-admin-ui.git
pipeline-tasks-git-branch: master
pipeline-tasks-git-url: https://github.com/18F/cg-pipeline-tasks.git

slack-icon-url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
slack-username: concourse
